package com.gtnewhorizon.cropsnh.fluids;

import java.awt.Color;

import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.util.StatCollector;
import net.minecraftforge.fluids.Fluid;
import net.minecraftforge.fluids.FluidContainerRegistry;
import net.minecraftforge.fluids.FluidRegistry;
import net.minecraftforge.fluids.FluidStack;

import com.gtnewhorizon.cropsnh.utility.ModUtils;

import gregtech.api.GregTechAPI;
import gregtech.api.enums.ItemList;
import gregtech.api.interfaces.IItemContainer;
import gtPlusPlus.core.item.base.BaseItemComponent;

public class CropsNHCellFluid extends Fluid implements Runnable {

    private final int mColor;

    public CropsNHCellFluid(String aName, Color aColor, String aCellItemName, IItemContainer aCellContainer) {
        super(aName);
        this.mColor = aColor.getRGB();

        // register the fluid
        FluidRegistry.registerFluid(this);
        GregTechAPI.sGTBlockIconload.add(this);

        // create cell item
        short[] cellRGBA = new short[] { (short) aColor.getRed(), (short) aColor.getGreen(), (short) aColor.getBlue(),
            (short) aColor.getAlpha() };
        Item cellItem = new BaseItemComponent(
            aCellItemName,
            this,
            StatCollector.translateToLocal(this.getUnlocalizedName()),
            cellRGBA);
        aCellContainer.set(new ItemStack(cellItem, 1, 0));

        // register it as a fluid container
        FluidContainerRegistry
            .registerFluidContainer(new FluidStack(this, 1000), aCellContainer.get(1), ItemList.Cell_Empty.get(1));
    }

    @Override
    public int getColor() {
        return this.mColor;
    }

    @Override
    public void run() {
        String ResourcePath = ModUtils.GregTech.getResourceLocation("fluids/fluid.autogenerated")
            .toString();
        setIcons(GregTechAPI.sBlockIcons.registerIcon(ResourcePath));
    }
}
